### ISSUE TITLE
Enhance SDK to load widgets based on wallet button hosting domain

### ISSUE THREAD

**Issue by cartonioh** [getmash/mash-js#107]
# Overview 
We need to support older versions of the mash script that use wallet.getmash.com in addition to any new script installations using app.mash.com. 

Widgets and wallet button need to be on the same domain in order to communicate with each other properly so we need to smarten up the sdk to ensure everything's loaded on the same domain, regardless of which integration variant we're dealing with.

These are variants we've seen so far:
- User added mash sdk script on **getmash.com** + auto-added widgets (hosted on **mash.com**)
- User added mash sdk script on **getmash.com** + manually added widgets (hosted on **getmash.com**)
- User added mash sdk script on **getmash.com** + manually added widgets (hosted on **getmash.com**) + auto-added widgets (hosted on **mash.com**)

- User is using mash sdk package `< 2.15.0` which uses **getmash.com** 
- User is using mash sdk package `>= 2.15.0` which uses **mash.com**

**Acceptance Criteria**
- [ ] Mash sdk should look at where it itself is being hosted and use that domain to auto-load widgets

**Comment by jnxdd** [comment]
@cartonioh is this done?
